POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "id": "234",
  "username": "test",
  "firstname": "Kirill",
  "lastname": "Legkodukh",
  "phoneNumber": "7-999-555-99-56",
  "email": "test1@gmail.ru",
  "password": "password",
  "sex": "male",
  "growth": "145",
  "weight": "123"
}
###
GET http://test:password@127.0.0.1:8080/user?id=23
WWW-Authenticate: Basic charset="UTF-8"
###

GET http://test:password@127.0.0.1:8080/user?email=test1@yandex.ru
###

PUT http://test:password@127.0.0.1:8080/user/15
Content-Type: application/json

{
  "id": "234",
  "username": "test",
  "firstname": "Kirill",
  "lastname": "Legkodukh",
  "phoneNumber": "7-999-555-99-99",
  "email": "test1@yandex.ru",
  "password": "password",
  "sex": "female",
  "growth": "145",
  "weight": "123"
}
###

DELETE http://test:password@127.0.0.1:8080/user?id=16
###

GET http://127.0.0.1:8080/users

###

GET http://test:password@127.0.0.1:8080/user?username=test

###
GET http://test:password@127.0.0.1:8080/user?id=23

###
GET http://test:password@127.0.0.1:8080/static/days_with_yoga.jpg

###
GET http://test:password@127.0.0.1:8080/static/kesheshi.jpg

###
GET http://test:password@127.0.0.1:8080/static/exercise_for_beginners.jpg

###
GET http://test:password@127.0.0.1:8080/static/scretch_for_you.jpg

###
GET http://test:password@127.0.0.1:8080/static/image.png

###
GET http://test:password@127.0.0.1:8080/static/scretch.png

###
GET http://test:password@127.0.0.1:8080/static/pic1.jpg

###
GET http://test:password@127.0.0.1:8080/static/pic2.jpg

###
GET http://test:password@127.0.0.1:8080/static/2290.jpg

###
GET http://test:password@127.0.0.1:8080/static/ph1.png
###
GET http://test:password@127.0.0.1:8080/static/ph2.png
###
GET http://test:password@127.0.0.1:8080/static/ph3.png
###
GET http://test:password@127.0.0.1:8080/static/ph4.png
###
GET http://test:password@127.0.0.1:8080/static/ph5.png
###
GET http://test:password@127.0.0.1:8080/static/ph6.png
###
GET http://test:password@127.0.0.1:8080/static/ph7.png
###
GET http://test:password@127.0.0.1:8080/static/ph8.png
